env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  GIT_EMAIL: arquitetura@involves.com
  GIT_USER: Buildkite
  
steps:
  - label: "Weekly dependencies update"
    key: "update"
    env:
      SCRIPT_NAME: .buildkite/run_tests.sh
    command:
      - git config --global user.email $$GIT_EMAIL
      - git config --global user.name $$GIT_USER
      - git checkout master && git fetch && git pull --rebase
      - docker build --target=dependencies-update --tag=$$BUILDKITE_BUILD_ID .
      - docker run --name=$$BUILDKITE_BUILD_ID $$BUILDKITE_BUILD_ID
      - docker cp $$BUILDKITE_BUILD_ID:/data/package.json .
      - docker rm -vf $$BUILDKITE_BUILD_ID
      - chmod +x ./$$SCRIPT_NAME
      - ./$$SCRIPT_NAME
      - git add package.json
      - git commit -m "[CI] Updating Dependencies (weekly)"
      - git push -u origin master
    soft_fail:
      - exit_status: 1
    agents:
      queue: "docker"
    if: build.source == "schedule"

  - label: "Lint"
    key: "lint"
    command:
      - docker build --tag=$$BUILDKITE_BUILD_ID --target=lint .
      - docker run --rm $$BUILDKITE_BUILD_ID
    agents:
      queue: "docker"
    if: build.source != "schedule"

  - label: "Tests"
    key: "test"
    env:
      SCRIPT_NAME: .buildkite/run_tests.sh
    command:
      - chmod +x ./$$SCRIPT_NAME
      - ./$$SCRIPT_NAME
    agents:
      queue: "docker"
    if: build.source != "schedule"

  - label: "Publish Library"
    key: "publish"
    command:
      # - git checkout master && git fetch && git pull --rebase
      # - git config --global user.email ${GIT_EMAIL}
      # - git config --global user.name ${GIT_USER}
      # - npm version patch -m "[skip ci] [CI] Bumping to %s"
      # - git push --tags -u origin master
      - npm publish
    agents:
      queue: "node16"
    depends_on:
      - "lint"
      - "test"
    if: build.source != "schedule" && build.branch == "master"
