env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  PROJECT_NAME: mysql2-lib
  PROJECT_TYPE: library
  TEAM_EMAIL: sdom@involves.com
  SCRIPTS_REPOSITORY: https://raw.githubusercontent.com/involvestecnologia/buildkite-helper/master/scripts
  
steps:
  - label: "Weekly dependencies update"
    key: "update"
    env:
      SCRIPT_NAME: dependencies-update.sh
    command:
      - "curl -s -O -H \"Authorization: token $$GITHUB_TOKEN\" $$SCRIPTS_REPOSITORY/$$SCRIPT_NAME"
      - chmod +x ./$$SCRIPT_NAME
      - ./$$SCRIPT_NAME
    soft_fail:
      - exit_status: 1
    agents:
      queue: "docker"
    if: build.source == "schedule"

  - label: "Tests"
    key: "test"
    env:
      SCRIPT_NAME: docker-compose-tests-with-cleanup.sh
    command:
      - "curl -s -O -H \"Authorization: token $$GITHUB_TOKEN\" $$SCRIPTS_REPOSITORY/$$SCRIPT_NAME"
      - chmod +x ./$$SCRIPT_NAME
      - ./$$SCRIPT_NAME
    agents:
      queue: "docker"
    if: build.source != "schedule"

  - label: "Publish Library"
    key: "publish"
    env:
      SCRIPT_NAME: publish-library.sh
    command:
      - "curl -s -O -H \"Authorization: token $$GITHUB_TOKEN\" $$SCRIPTS_REPOSITORY/$$SCRIPT_NAME"
      - chmod +x ./$$SCRIPT_NAME
      - ./$$SCRIPT_NAME
    agents:
      queue: "docker"
    depends_on:
      - "test"
    if: build.source != "schedule" && build.branch == "master"