env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  PROJECT_NAME: mysql2-lib
  
steps:
  - label: "Weekly check for updates"
    key: "update"
    command: >
      git config --global user.email "sdom@involves.com";
      git config --global user.name "Buildkite";
      git checkout master && git fetch && git pull --rebase;
      docker build --target=dependencies-update --tag=${PROJECT_NAME} .;
      docker run --name=${PROJECT_NAME} ${PROJECT_NAME};
      docker cp ${PROJECT_NAME}:/data/package.json .;
      docker rm -vf ${PROJECT_NAME};
      docker-compose build --pull;
      docker-compose run test;
      docker-compose down;
      git add package.json;
      git commit -m "updating dependencies";
      git push -u origin master;
    soft_fail:
      - exit_status: 1
    agents:
      queue: "docker"
    if: build.source == "schedule"

  - label: "Tests"
    key: "test"
    command:
      - "docker-compose build --pull"
      - "docker-compose run test"
      - "docker-compose down"
    agents:
      queue: "docker"
    if: build.source != "schedule"

  - label: "Publish Library"
    key: "publish"
    command: >
      git config --global user.email "sdom@involves.com";
      git config --global user.name "Buildkite";
      git checkout master && git fetch && git pull --rebase;
      docker build --build-arg NPM_TOKEN=${NPM_TOKEN} --tag=${PROJECT_NAME} --target=publish .;
      docker run --name=${PROJECT_NAME} ${PROJECT_NAME};
      docker cp ${PROJECT_NAME}:/data/package.json .;
      docker rm -vf ${PROJECT_NAME};
      git add package.json;
      git commit -m "[skip ci] Bumping version";
      git push -u origin master;
    agents:
      queue: "docker"
    depends_on:
      - "test"
    if: build.source != "schedule" && build.branch == "master"